### ISSUE TITLE
Testing Dataset

### ISSUE THREAD

**Issue by Olan-Pinto** [JimmyChame/SADNet#13]
Hi could you please provide the dataset for testing

**Comment by JimmyChame** [comment]
The testing and training datasets could be found here:
1. CBSD68: [https://github.com/clausmichele/CBSD68-dataset](url)
2. Kodak24: [http://r0k.us/graphics/kodak/](url)
3. Nam: [http://snam.ml/research/ccnoise](url)
4. DND: [https://noise.visinf.tu-darmstadt.de/](url)
5. SIDD: [https://www.eecs.yorku.ca/~kamel/sidd/dataset.php](url)
6. RENOIR: [http://ani.stat.fsu.edu/~abarbu/Renoir.html](url)
7. PolyU: [https://github.com/csjunxu/PolyU-Real-World-Noisy-Images-Dataset](url)
