### ISSUE TITLE
cuda available issue

### ISSUE THREAD

**Issue by Sishxo** [JimmyChame/SADNet#14]
I've already finished the install step.
When I try to run the test.py, I met the error "There are not available cuda devices!"
But I've already had the cuda and cudnn in my environment which can be used in other times, **_and  I add this line "print(torch.cuda.is_available())" in the main func of the test.py, it returns True to me._**
**_But when it was the same 'torch.cuda.is_available()' in the evaluate_net() func , it turns into false._**
Could you please help me to solve this problem?
![image](https://user-images.githubusercontent.com/54496724/160242201-56b99b0b-23cb-4d59-a08a-bff25808c438.png)

**Comment by JimmyChame** [comment]
I am sorry for being late. I guess maybe the gpu number you specified is not in your gpu sequence. You can change the args.gpu according to your environment.

**Comment by LinJiangJiang** [comment]
请问电脑没有独立显卡，还可以测试数据集吗

**Comment by JimmyChame** [comment]
当然是可以的，但是需要将模型和数据加载到cpu上测试，速度会比较慢。
