### ISSUE TITLE
initialization method during training

### ISSUE THREAD

**Issue by mosquitobite** [JimmyChame/SADNet#2]
Hi, thanks for sharing! I wonder  when training conv2d for deformable conv_offset_mask, can the default xaiver uniform initialization method  work? 
In the original paper of DCN, the initilization method is constant zeros. which can prevent loss from exploding. 
And have you tried effects of different initialization methods for conv_offset_mask learning? Personally, I think initialization method matters since deformable convolution is quite sensitive.

**Comment by JimmyChame** [comment]
Thanks for your advice. I just use the default initilization method in the DCN, and it can obtain good results. Initialization methods do have an impact on the results, and we will test them more extensively in the future work.
