### ISSUE TITLE
Why RSABs are not used at encoder?

### ISSUE THREAD

**Issue by mosquitobite** [JimmyChame/SADNet#3]
Hi, from ablation study in your paper, RSAB without offset transfer seems to achieve the most denoising performance.   Since RSAB without offset transfer can be used at encoder, why not do that? Intuitively, performance could  be much better.

**Comment by JimmyChame** [comment]
Thanks for your advice. Offset transfer and context block assist RSAB in better locating feature offsets. RSAB with offset transfer achieves the best performance. We calculate the offset maps from coarse to fine in the multiscale structure.
