### ISSUE TITLE
What is the different between ModulatedDeformConvPack2 and ModulatedDeformConvPack

### ISSUE THREAD

**Issue by wenchen4321** [JimmyChame/SADNet#6]
Hello, would you tell me What is the difference between **_ModulatedDeformConvPack2_** in **_dcn.deform_conv_** and **_ModulatedDeformConvPack_** in **_dcn.deform_conv_**? The code of them are same.

**Comment by JimmyChame** [comment]
ModulatedDeformConvPack2  make a little modified on the orginal ModulatedDeformConvPack. We can control the input offset channels to compute the offset maps.
